/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveDetailDrawer: typeof import('./../components/ArchiveDetailDrawer.vue')['default']
    ArchiveDownloadDialog: typeof import('./../components/ArchiveDownloadDialog.vue')['default']
    ArchiveSection: typeof import('./../components/ArchiveSection.vue')['default']
    ArchiveTable: typeof import('./../components/ArchiveTable.vue')['default']
    ConnectionFormDrawer: typeof import('./../components/ConnectionFormDrawer.vue')['default']
    ConnectivityBadge: typeof import('./../components/ConnectivityBadge.vue')['default']
    DangerConfirm: typeof import('./../components/DangerConfirm.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnvironmentDialog: typeof import('./../components/EnvironmentDialog.vue')['default']
    EnvironmentTree: typeof import('./../components/EnvironmentTree.vue')['default']
    HostKeyDialog: typeof import('./../components/HostKeyDialog.vue')['default']
    LocalArtifactCard: typeof import('./../components/LocalArtifactCard.vue')['default']
    PipelinePanel: typeof import('./../components/PipelinePanel.vue')['default']
    PublishPanel: typeof import('./../components/PublishPanel.vue')['default']
    ReconcileDialog: typeof import('./../components/ReconcileDialog.vue')['default']
    RecoveryDialog: typeof import('./../components/RecoveryDialog.vue')['default']
    RollbackDialog: typeof import('./../components/RollbackDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptPanel: typeof import('./../components/ScriptPanel.vue')['default']
    TargetDetail: typeof import('./../components/TargetDetail.vue')['default']
    TargetWizard: typeof import('./../components/TargetWizard.vue')['default']
    TaskConsole: typeof import('./../components/TaskConsole.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
